version: '3'
services:
  db:
    build: .
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    tty: true
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: {}
